baseURL: "https://ajsquestions.github.io/" 
title: AJ
theme: PaperMod

pagination:
    pagerSize: 20

enableInlineShortcodes: true
enableRobotsTXT: true

menu:
    main:
        - name: About
          url: /about/
          weight: 1
        - name: CV
          url: /AJ_CV_Sep25.pdf
          weight: 2
        - name: Research
          url: /research/
          weight: 3
        - name: Teaching
          url: /teaching/
          weight: 4
        - name: Projects
          url: /projects/
          weight: 5
        - name: Questions
          url: /questions/
          weight: 6
        - name: Contact
          url: /contact/
          weight: 7

params:
    description: "Financial Data Science | PhD @ UCLA Anderson | HBS | Booth | IIM-B | MS FinMath UChicago"
    author: AJ
    googleAnalyticsID: ""
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: true
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: AJ
          subtitle: "Financial Data Science | PhD @ UCLA Anderson | HBS | Booth | IIM-B | MS FinMath UChicago"
          imageUrl: "/AJpicture.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: AJ
          buttons:
            - name: About
              url: /about/
              weight: 1
            - name: CV
              url: /AJ_CV_Sep25.pdf
              weight: 2
            - name: Research
              url: /research/
              weight: 3
            - name: Teaching
              url: /teaching/
              weight: 4
            - name: Projects
              url: /projects/
              weight: 5
            - name: Questions
              url: /questions/
              weight: 6
            - name: Contact
              url: /contact/
              weight: 7
    socialIcons:
        - name: CV
          url: /AJ_CV_Sep25.pdf
        - name: Email
          url: mailto:aryaman.jena5000@gmail.com
        - name: LinkedIn
          url: https://www.linkedin.com/in/aj-jena-13b738172/
        - name: GitHub
          url: https://github.com/ajsquestions

    assets:
        disableHLJS: false
        disableScrollBarStyle: false
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "AJ"
      icon: "/favicon-16x16.png"
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: monokai
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
